### ISSUE TITLE
Search for accommodation requests 

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#100]
**Story:** as a user I want t search for all available accommodation requests (without restrictions) in order to see all published ads, where the accommodations are sought.

 - [ ] AC1: In the category accommodation I select Request /Anfragen and than select search. As result all published requests will be presented as search results.

-------
DoD

  - [ ] Story is tested against acceptance criteria
  - [ ] Unit test should be passed
  - [ ] Integration test is done ( if applicable)
  - [ ] Non-functional requirements are met
  - [ ] Story ok-ed by Product Owner
  - [ ] Peer Code Review performed
  - [ ] Any configuration or build changes documented
