### ISSUE TITLE
Login with Active-Directory account

### ISSUE THREAD

**Issue by TimmyAeberli** [AkrosAG/Akros-Marketplace#11]
Story: As Akros employee I want to login in Marketplace application with active directory authentication (without the password) so that I can log in (to subsequently create or edit an ad).

Acceptance criteria:

- [x] Implement Options Menu (Button [SOME ICON]) at the top of each page, which opens up a menu. **Will be done in a later task with high fidelity mockup**
- [ ] Login modal appears as soon as user want to create ad.
- [ ] (SL) Fixing the HTTPS-Problem: Not working as expected when using secure protocol. Debugging & research task.
- [ ] negative case: if user don't have Akros ID, appropriate message should appear.

https://akroscontentteam.invisionapp.com/console/share/NC2D7WK5MQH/874941363

![image](https://user-images.githubusercontent.com/41478805/154071011-2c1eef5c-9399-4452-b33b-61767a5e44a9.png)

**Comment by fingeririna** [comment]
As Akros employee I want to login in Marketplace application with active directory authentication (without the password) so that I can create or update the ad.
