### ISSUE TITLE
Search Filter

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#112]
**Story:** As a user I want to be able to change and adjust search criteria on the fly 

https://akrosag-my.sharepoint.com/:x:/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA

exclude search for "+km" -> see story....

Acceptance Criteria:

- [ ] Show the search fields used for the search as in excel and category-tree (category, subcategory etc.).
- [ ] Be able to change those values and have a update of the results (with apply-button).
- [ ] Show no results if no matches are found (instead some kind of message).

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/41478805/167857484-59cd75d5-c88c-42f2-b3ea-1927fd004312.png">

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/41478805/167858031-90d03903-70e3-4c54-b72d-7c276dd0dd90.png">

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/41478805/167859072-ecdb3e92-3cf8-4869-9ba7-aa51f38e18f1.png">

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/41478805/167859182-ed101bcd-b445-4e94-a09a-89e03bb2c673.png">

**Comment by akrguda** [comment]
This ticket is closed because the new wishes of Heinz to use new technologies.
