### ISSUE TITLE
Default search accommodation: no results

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#27]
**Story:** As a user I want to search for category accommodation in order to get as search result of all ads belongs to this category. If no results are found, a corresponding message is displayed.

- [x] separat task for API #6  - should be implement before

**AC1:** If no ads exist in category accommodation, following message will be shown: 
           - DE: Die gesetzten Suchkriterien haben leider keinen Treffer ergeben.
           - EN: Unfortunately your search criteria produced no result.

- [x] Create new component for search results and navigate to it under 'search-results'
- [x] Display text message horizontally and vertically aligned (design TBD if needed), and logic to display it based on if results object is empty

![image](https://user-images.githubusercontent.com/96523998/156384432-c81718a5-9854-481c-977d-7e31ddba5d57.png)

DoD
- [ ] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented

**Comment by stefanleminh** [comment]
The current state is that the UI-Component is implemented and already gets the category fields but the search itself doesn't work yet.
