### ISSUE TITLE
Search for apartment or house offers

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#28]
**Story:** As a user I want to be able to search for apartments or houses by specifying some selection criteria, in order to quickly find an apartment or house that suits my needs.

[https://akrosag-my.sharepoint.com/❌/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA](https://akrosag-my.sharepoint.com/:x:/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA)

_Acceptance criteria:_
- [x] AC1: In the category Accomodation I select Apartment & Offer and get the search criteria for apartment offer as in excel above.
- [x] AC2: In the category Accomodation I select House & Offer and get the search criteria for house offer as in excel above.
- [x] AC3: I select multiple criteria and get the results for apartment offers accordingly
- [x] AC4: I select multiple criteria and get the results for house offers accordingly
----------------------------------
Definition of Done
- [x] Story is tested against acceptance criteria
- [x] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented
- [ ] Any database changes are documented [Database](https://github.com/AkrosAG/Akros-Marketplace/wiki/Database)

**Comment by blanchekenneth** [comment]
SW was tested by Stephanie at 34.10.2022.


[#28 & #142.xlsx](https://github.com/AkrosAG/Akros-Marketplace/files/9849680/28.142.xlsx)


drag excel table to attachment

**Comment by Dummylearners** [comment]
This User story and AC  from 1 to 4 are already tested by Stephanie 07.10.2022. Test Document is updated. No Testing action is pending.

This ticket may be moved from here, thanks @LanaKast
