### ISSUE TITLE
Create room ad

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#33]
**Story:** As a user I want to post an ad for room to rent.

I can give 
- Title
DE: Titel*
EN: Title
- brief description of the accommodation, a size, floor, no. of rooms etc.
DE: Miete (CHF)*
EN: Rent (CHF)
DE: Preiseinheit (pro Monat, pro Woche, pro Tag)*
EN: Price unit (per month, per week, per day)
DE: Zimmer*
EN: Rooms
DE: Etage
EN: Floor
DE: Wohnfläche (m2)
EN: Living space (m2)
- time frame*  ----> Story #54
- adress (region, town/village) 
DE: Strasse, Nr.*
EN: Address, No.
DE: PLZ, Ort* ----->Story #49 
EN: Zipcode, City*
DE: Land -----> Story #50 --> rejected
EN: Country
- Description* ( location and surroundings) 
EN: Furnisching (yes, no)
DE:
DE:
EN:
- my expectation on the tenant 
DE:
EN:
- brief description about me - the I seek and I am
DE:
EN:
- my contact adress* - Telefonnummer ( text area )

This story is related to #41 

Example:
![image](https://user-images.githubusercontent.com/96523998/157472956-aa535f73-631a-446b-a80b-4319ffb907eb.png)

I can upload pictures -> not part of this Story, but Story  #48  and #50

- [x] Revise, and adapt if needed, the database script to have all fields needed for the creation.
- [x] Validations for the fields: required fields, date control, numeric fields, format for (email, phone, postal code), max chars for (title, description and short description)

-----------------------------------------------------------------------------------------------------

Here is a snippet of the Navigation Flow diagram

![image](https://user-images.githubusercontent.com/96523998/154031452-823318a4-ebe3-431e-b46e-0dfa120e2df5.png)

----------------
DoD
- [x] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [x] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented

**Comment by nobu-koil** [comment]
https://akroscontentteam.invisionapp.com/console/share/NC2D7WK5MQH/881101140

**Comment by fingeririna** [comment]
![image](https://user-images.githubusercontent.com/96523998/165243059-7e1352d2-cc12-4353-8019-605f84bce9c5.png)
