### ISSUE TITLE
Presenting accommodation offers search results

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#37]
**Story:** as a user I want to see in the search results a short overview of the room offers

AC1: For every offer founded I see
       - ~~picture~~ Will be implemented with #48 and #52 
       - price
       - room in a shared flat
       - adress

AC2: I select an image and will be forwarded to a detailed view. Story #63 

-------------------------------

Design: Story #66 

- [x] Implement the View for Results
- [x] Create new page for detailed view, passing data through input
- [x] Routing

DoD
- [ ] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented

**Comment by fingeririna** [comment]
As in a current view, following information is persenting in the Search Results near the picture:
- [x] Title
- [x] Price /CHF
- [x] Adress

Bug:
- [ ] adress should be in one row, not like currently in two
