### ISSUE TITLE
Function "Post ad" on the Homepage

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#39]
**Story:** On the Homepage of AM I can easily find a function «post ad» ("create an ad") so that I can start the ad creation.

_Acceptance criteria:_
- [ ] The "Create an Ad" button can be easily found on the home page, without scrolling on the UI, e.g. in the header.
- [ ] The "Create an Ad" button can be selected and the system show the first page of ad creation (in case the user already logged in)
- [ ] The brief description (Title) is available above the button 
       -  EN: Post Your Adverticement for Free
       -  DE: Erstellen Sie einen kostenloses Inserat

![image](https://user-images.githubusercontent.com/96523998/155104521-027b6db9-92e1-4024-8df1-c51291b55231.png)

Tasks:
- [ ] Apply Styles
- [ ] Adjust Title
- [x] Create new Angular component
