### ISSUE TITLE
Create ad: Time Frame

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#54]
**Story:** As a user I want to give the time frame of acommodation availability in my offer ad. 

---------------------
Availability:

> DE: Verfügbar* 

   - Ab Datum (default)
   - Ab sofort
   - Auf Anfrage

> EN: Available* 

   - Specific date
   - immediately
   - by agreement

> DE: Umzugsdatum (TT.MM.JJJJ) ---> activ and mundatory only if "Specific Date" is selected

> EN: Moving Date (DD.MM.YYYY)

> DE: Befristet  (yes/no), default "no"

> EN: Temporary 
-------------------
_Acceptance Criteria:_

- [x] AC1: I can select one of 3 options of availability
- [x] AC2: If I select "Specific date", I can put the moving day (DD.MM.YYYY). 
            Date Validation: 
           - format (?)
           - the date must not lie in the past (?) 
- [x] AC3: I can select "Temporary" yes/no

---------------------

![image](https://user-images.githubusercontent.com/96523998/157639297-29f8f06f-b241-4799-83c5-47663a24cd2e.png)

Tasking
- [x] Adapt the design
- [x] Adapt the database structure
- [x] Date validation

DoD
- [x] Story is tested against acceptance criteria
- [x] Unit test should be passed
- [x] Integration test is done ( if applicable)
- [x] Non-functional requirements are met
- [x] Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented
